# Site settings
title:          youhy's
description:    "Minimal Jekyll theme for storytellers"
baseurl:        ""
url:            "https://chesterhow.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         youhy
  url:          https://github.com/AzulRadio
  email:        hy19@illinois.edu

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec, vendor ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale
